server:
  port: 9077

spring:
  security:
    basic:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.139/ss?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root123


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true